### ISSUE TITLE
Crash when using showPicker with RN 0.57.4

### ISSUE THREAD

**Issue by ferdicus** [aakashns/react-native-dialogs#101]
__RN-Version:__ 0.57.4
**lib version:** 1.0.2

I'm getting the following crash when selecting a radio button on the picker spawned with the following code:
```
      const { selectedItem } = await DialogAndroid.showPicker(
        'Select one',
        'anyone',
        {
          positiveText: 'OK',
          negativeText: Cancel,
          items: [
            { label: 'aaa', id: 'a' },
            { label: 'bbb', id: 'b' },
            { label: 'ccc', id: 'c' }
          ],
          selectedId: 'a',
          type: DialogAndroid.listRadio
        }
      );
```

Below the log from `adb logcat`
<details><summary>Show Logs</summary>

```
----------------
I'm assuming it has something to do with a mismatch in the dependencies between my react-native gradle and the ones loading/ needed for this?


--------- beginning of crash
11-14 09:19:52.682 10378 10378 E AndroidRuntime: FATAL EXCEPTION: main
11-14 09:19:52.682 10378 10378 E AndroidRuntime: Process: com.MYAPP, PID: 10378
11-14 09:19:52.682 10378 10378 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.support.v7.widget.DefaultItemAnimator.resetAnimation(DefaultItemAnimator.java:514)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.support.v7.widget.DefaultItemAnimator.animateChange(DefaultItemAnimator.java:321)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.support.v7.widget.SimpleItemAnimator.animateChange(SimpleItemAnimator.java:149)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.animateChange(RecyclerView.java:3510)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3320)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3080)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.view.View.layout(View.java:18856)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5954)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.view.View.layout(View.java:18856)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5954)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.view.View.layout(View.java:18856)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5954)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at com.afollestad.materialdialogs.internal.MDRootLayout.onLayout(MDRootLayout.java:259)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.view.View.layout(View.java:18856)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5954)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.view.View.layout(View.java:18856)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5954)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.view.View.layout(View.java:18856)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5954)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:908)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.view.View.layout(View.java:18856)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.view.ViewGroup.layout(ViewGroup.java:5954)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2652)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2368)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1519)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7113)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:702)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:638)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6780)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1500)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1390)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.animation.AnimatorCompatHelper" on path: DexPathList[[zip file "/data/app/com.MYAPP-1/base.apk"],nativeLibraryDirectories=[/data/app/com.MYAPP-1/lib/arm, /data/app/com.MYAPP-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
11-14 09:19:52.682 10378 10378 E AndroidRuntime: 	... 50 more

```
</details>

-------

I'm assuming it's based on a mismatch of my app dependencies vs the dependencies this lib needs?

I'm using `compile "com.android.support:appcompat-v7:26.0.1"`

**Comment by ThanakornNitsiri** [comment]
try this

implementation 'com.android.support:design:27.1.1’
implementation 'com.android.support:support-v4:27.1.1’

**Comment by vonovak** [comment]
closing as answered
