### ISSUE TITLE
App crashes: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.getColor(int)' on a null object reference

### ISSUE THREAD

**Issue by amit-Newput** [aakashns/react-native-dialogs#22]
I have used this module in an app and some times it gives me following error:

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.getColor(int)' on a null object reference
    at com.afollestad.materialdialogs.util.DialogUtils.getColor(DialogUtils.java:115)
    at com.afollestad.materialdialogs.MaterialDialog$Builder.<init>(MaterialDialog.java:477)
    at com.aakashns.reactnativedialogs.modules.DialogAndroid.show(DialogAndroid.java:119)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:271)
    at com.facebook.react.bridge.NativeModuleRegistry$ModuleDefinition.call(NativeModuleRegistry.java:183)
    at com.facebook.react.bridge.NativeModuleRegistry.call(NativeModuleRegistry.java:62)
    at com.facebook.react.bridge.CatalystInstanceImpl$NativeModulesReactCallback.call(CatalystInstanceImpl.java:421)
    at com.facebook.react.bridge.queue.NativeRunnableDeprecated.run(Native Method)
    at android.os.Handler.handleCallback(Handler.java:746)
    at android.os.Handler.dispatchMessage(Handler.java:95)
:   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    at android.os.Looper.loop(Looper.java:148)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:187)
    at java.lang.Thread.run(Thread.java:818)

I have found following link which may be helpful:
https://github.com/domoticz/domoticz-android/issues/267

**Comment by Fuhrmann** [comment]
At the time of this writing this library is using:

com.github.afollestad.material-dialogs:commons:0.8.6.2

So I guess this is not an issue anymore.

**Comment by vonovak** [comment]
Thanks for helping out @Fuhrmann!
