### ISSUE TITLE
Crash on app load

### ISSUE THREAD

**Issue by dkan** [aakashns/react-native-dialogs#70]
After installing this package the app builds, but crashes on load with the following error:   

```
09-18 12:19:00.442 7174-7211/? E/AndroidRuntime: FATAL EXCEPTION: mqt_js
                                                 Process: com.app, PID: 7174
                                                 java.lang.IncompatibleClassChangeError: The method 'java.io.File android.support.v4.content.ContextCompat.getNoBackupFilesDir(android.content.Context)' was expected to be of type virtual but instead was found to be of type direct (declaration of 'com.google.android.gms.iid.zzd' appears in /data/app/com.app-1/base.apk)
                                                     at com.google.android.gms.iid.zzd.zzdo(Unknown Source)
                                                     at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                                                     at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                                                     at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
                                                     at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
                                                     at com.learnium.RNDeviceInfo.RNDeviceModule.getConstants(RNDeviceModule.java:112)
                                                     at com.facebook.react.bridge.JavaModuleWrapper.getConstants(JavaModuleWrapper.java:140)
                                                     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
                                                     at java.lang.Thread.run(Thread.java:761)
```

Using `react-native 0.48.1` and `react-native-dialogs 0.0.19`

Can get the app to run properly by removing the `react-native link` generated code, but then obviously, I can't use the package.

Any idea what is wrong? I know nothing about developing for Android.

**Comment by vonovak** [comment]
when developing on android, the stacktrace gives you information about what went wrong. when looking at it, you'll see, among others `com.facebook.react.bridge.JavaModuleWrapper.getConstants(JavaModuleWrapper.java:140)`which is where the error may come from. Also, I'm surprised you compiled the code, the latest release should not be compatible with 0.48. as far as I know

**Comment by dkan** [comment]
It appears that this library depends on a `com.google.android.gms:play-services-gcm` being > than a specific version, and mine was force set. Closing this issue as it is not a problem with this library.
