### ISSUE TITLE
RuntimeException: This callback type only permits a single invocation from native code.

### ISSUE THREAD

**Issue by varungupta85** [aakashns/react-native-dialogs#92]
I am experiencing these two exceptions after I migrated to the latest version i.e. `1.0.1`. The errors occur either in the process of showing an alert or when clicking one of the buttons in the alert. There are two callstacks seen on Sentry. Below is the code that I am using to show the alert. I thought one of the goals of the overhaul of the API was to get rid of multiple invocation errors. Please let me know how can I fix this problem. It is not happening in my debug environment due to which I am not able to run it in debugger.

```javascript
const showAlert = async (title, message, buttons, cancelable = true) => {
      const validButtons = buttons ? buttons.slice(0, 3) : [{text: I18n.t('ok')}];
      const buttonPositive = validButtons.pop();
      const buttonNegative = validButtons.pop();
      const buttonNeutral = validButtons.pop();

      const options = {
        title: title && title !== '' ? title : undefined,
        content: message && message !== '' ? message : undefined,
        positiveText: buttonPositive ? buttonPositive.text :  undefined,
        positiveColor: buttonPositive && buttonPositive.style && buttonPositive.style === 'destructive' ? colorThemes.Blue.red : colorThemes.Blue.primary,
        negativeText: buttonNegative ? buttonNegative.text :  undefined,
        negativeColor: buttonNegative && buttonNegative.style && buttonNegative.style === 'destructive' ? colorThemes.Blue.red : colorThemes.Blue.primary,
        neutralText: buttonNeutral ? buttonNeutral.text :  undefined,
        neutralColor: buttonNeutral && buttonNeutral.style && buttonNeutral.style === 'destructive' ? colorThemes.Blue.red : colorThemes.Blue.primary,
        cancelable: cancelable
      }
      const { action } = await DialogAndroid.alert(title, message, options);
      switch (action) {
        case DialogAndroid.actionPositive:
            buttonPositive && buttonPositive.onPress && buttonPositive.onPress()
            break;
        case DialogAndroid.actionNegative:
            buttonNegative && buttonNegative.onPress && buttonNegative.onPress()
            break;
        case DialogAndroid.actionNeutral:
            buttonNeutral && buttonNeutral.onPress && buttonNeutral.onPress()
            break;
        case DialogAndroid.actionDismiss:
            break;
      }
  }
```

```java
RuntimeException
Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
com.facebook.react.bridge.CallbackImpl in invoke at line 28
com.aakashns.reactnativedialogs.modules.DialogAndroid$4 in onClick at line 240
com.afollestad.materialdialogs.MaterialDialog in onClick at line 396
android.view.View in performClick at line 6897
android.widget.TextView in performClick at line 12653
android.view.View$PerformClick in run at line 26097
android.os.Handler in handleCallback at line 789
android.os.Handler in dispatchMessage at line 98
android.os.Looper in loop at line 164
android.app.ActivityThread in main at line 6940
Called from: java.lang.reflect.Method in invoke
com.android.internal.os.Zygote$MethodAndArgsCaller in run at line 327
com.android.internal.os.ZygoteInit in main at line 1374
```

```java
RuntimeException
Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
com.facebook.react.bridge.CallbackImpl in invoke at line 28
com.aakashns.reactnativedialogs.modules.DialogAndroid$11 in onDismiss at line 351
android.app.Dialog$ListenersHandler in handleMessage at line 1503
android.os.Handler in dispatchMessage at line 105
android.os.Looper in loop at line 164
android.app.ActivityThread in main at line 6940
Called from: java.lang.reflect.Method in invoke
com.android.internal.os.Zygote$MethodAndArgsCaller in run at line 327
com.android.internal.os.ZygoteInit in main at line 1374
```

**Comment by Noitidart** [comment]
Does this happen only when `cancelable` is true?

**Comment by varungupta85** [comment]
I have not tried with `cancelable` set to `false`. I can try with that also but it is common for dialog box to disappear when tapped outside the dialog box in Android.

**Comment by varungupta85** [comment]
@Noitidart I am experiencing the above abort with `cancelable` set to `false` also. Please let me know if you have any ideas about could be wrong since I am not able to reproduce this in my local dev environment. I don't mind dabbing with the JS or Java side code.

**Comment by Noitidart** [comment]
Can you give me exact args that are being passed to `DialogAndroid.alert` that causes this please.

**Comment by varungupta85** [comment]
Below are the exact arguments:

```javascript
const options = {
        title: 'Respond',
        content: null,
        positiveText: 'Accept',
        positiveColor: '#039BE5',
        negativeText: 'Decline',
        negativeColor: '#039BE5',
        neutralText: 'Later',
        neutralColor: '#039BE5',
        cancelable: true     // I tried both true and false
      }

const { action } = await DialogAndroid.alert('Respond', null, options);
      switch (action) {
        case DialogAndroid.actionPositive:
            // Run some code
            break;
        case DialogAndroid.actionNegative:
            // Run some code
            break;
        case DialogAndroid.actionNeutral:
            // Run some code
            break;
        case DialogAndroid.actionDismiss:
            // No code here
            break;
      }
```

**Comment by varungupta85** [comment]
@Noitidart I was looking at the code in `DialogAndroid.java` file. I see below method

```java
@ReactMethod
    public void list(ReadableMap options, final Callback callback)
```

but it is not used anywhere. Is this required? I want to wrap the `show` call in a try/catch to avoid the aborts for now. I saw that the callback is invoked in the `list` method also but the list method is not used anywhere. So, was wondering.

**Comment by Noitidart** [comment]
Thanks @varungupta85 ! I will look into this more closely tomorrow please.

**Comment by Noitidart** [comment]
@varungupta85 I tested it and it's not crashing for me. I tried all three buttons and dismissing via pressing in bacground, and also back button.

The java side is also working as expected.

Do you have `compile "com.android.support:appcompat-v7:23.0.1"` in your `app/build.gradle`?

Also I have this in build.gradle:

```
android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"

    defaultConfig {
        applicationId "com.did"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
```

**Comment by varungupta85** [comment]
@Noitidart I use `implementation "com.android.support:appcompat-v7:27.1.1"` and build against version `27.0.3`. I think the problem is with the `dismissListener`. Like I said earlier, it is not reproducible on all devices but some and on those devices, it is seen rather consistently. I tried changing the whole package to use promises instead of callbacks only to realise that the internally, promises also use callbacks. The reason I said it is due to `dismissListener` is because when I changed the implementation to use promises instead of callbacks, I removed all the checks of whether the callback has been called or not and then I was able to consistently see the `callback called more than once` crash on all devices as soon as I choose any button in the alert box. So, I guess when a user taps on any button, the underlying `material-dialogs` library is first calling the dialog action and then the dismiss action and since we only pass one function to the native side, that function end up getting called twice and hence the abort. I think the reason the reason the abort is only seen on some devices could be due to some synchronisation issue due to which the `mCallbackConsumed` flag is not set in time and we end up calling the callback twice. If you think about it, the only reason we have those checks is to avoid calling the callback twice which shouldn't happen in the first place. I ended up removing the `dismissListener` as well and now I don't see the abort any more.

**Comment by Noitidart** [comment]
Ooo device specific. Then this is an excellent bug you found, I'll work more on it tonight.

**Comment by varungupta85** [comment]
Okay. I think due to limitation of `react-native` due to which a callback can't be called twice, we should avoid running into it by removing the `dismissListener` and recommend users to make the dialog box `uncancelable` and provide a `Dismiss` button if they want to perform some action when user wants to only dismiss the dialog box. I can submit my changes as a PR if you are interested where I have moved the whole implementation to promises on the native side and also removed the `dismissListener` and the `mCallbackConsumed` check.

**Comment by vonovak** [comment]
If something can happen multiple times, we should be dispatching events (https://github.com/aakashns/react-native-dialogs/issues/57#issuecomment-350587541), not limiting users by saying they should not use dismissable dialogs.

Also, the problem with the library as it currently is, is that it has a promise-based interface but internally works with callbacks. It would be much better if it worked with promises all the way from JS to native as well.

**Comment by Noitidart** [comment]
Events would be awesome. I'll take a look into it this week.

**Comment by Noitidart** [comment]
In java is there an equivalent of the `setTimeout` trick to get it on "next tick"? I think this might fix the issue.

**Comment by Noitidart** [comment]
Actually @varungupta85 I think this is a simple fix. In my latest update, I made `onAny` required. So let's try by commenting out:

```
        // if (options.hasKey("onPositive")) {
        //     mBuilder.onPositive(new MaterialDialog.SingleButtonCallback() {
        //         @Override
        //         public void onClick(MaterialDialog materialDialog, DialogAction dialogAction) {
        //             if (!mCallbackConsumed) {
        //                 mCallbackConsumed = true;
        //                 callback.invoke("onPositive");
        //             }
        //         }
        //     });
        // }

        // if (options.hasKey("onNegative")) {
        //     mBuilder.onNegative(new MaterialDialog.SingleButtonCallback() {
        //         @Override
        //         public void onClick(MaterialDialog materialDialog, DialogAction dialogAction) {
        //             if (!mCallbackConsumed) {
        //                 mCallbackConsumed = true;
        //                 callback.invoke("onNegative");
        //             }
        //         }
        //     });
        // }

        // if (options.hasKey("onNeutral")) {
        //     mBuilder.onNeutral(new MaterialDialog.SingleButtonCallback() {
        //         @Override
        //         public void onClick(MaterialDialog materialDialog, DialogAction dialogAction) {
        //             if (!mCallbackConsumed) {
        //                 mCallbackConsumed = true;
        //                 callback.invoke("onNeutral");
        //             }
        //         }
        //     });
        // }
```

**Comment by Noitidart** [comment]
@varungupta85 You're right, the `list` method on the java side is not used by me. It was there in old version, but it was not documented. Let's remove it.

**Comment by Noitidart** [comment]
@varungupta85 please try this branch - https://github.com/aakashns/react-native-dialogs/tree/issue92

    npm i github:aakashns/react-native-dialogs#issue92

**Comment by Noitidart** [comment]
I'm actually very sure this should fix it. Because `builder.onPositive` `onNegative` `onNeutral` are no longer being used in v1. I am always sending `onAny` `true` from the js side, except for `showProgress` dialog.

**Comment by varungupta85** [comment]
@Noitidart Sorry for the late response. I didn't see your messages till now. I am not sure how would removing `onPositive`, `onNegative` or `onNeutral` help because I was any way not providing those callbacks in the `options`, so they would never be invoked any way. Like I said, I think the problem is that the underlying `material-dialogs` library invokes both the `action` and the `onDismiss` handlers when user chooses an action that sometimes leads to a race condition and hence the abort. I could try testing your branch but since you still have the `mCallbackConsumed` flag, the abort will be intermittent and I wouldn't know if it is working or not for sure. Other way of fixing the problem could be to pass separate `action` and `onDismiss` handlers to the java side code so that they could both be invoked at the same time. I have mentioned the solution in the PR also. I think the litmus test for me would be to remove the `mCallbackConsumed` flag and still have it work.

**Comment by Noitidart** [comment]
@varungupta85 did you get a chance to test this branch - https://github.com/aakashns/react-native-dialogs/issues/92#issuecomment-412324888 - ?

**Comment by Relax594** [comment]
I'm getting this issue aswell.

`java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
        at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:28)
        at com.aakashns.reactnativedialogs.modules.DialogAndroid$11.onDismiss(DialogAndroid.java:356)
        at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1350)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:6274)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`


using it like that 

`const { action, text } = await DialogAndroid.prompt(title, dialogDescription, {
      defaultValue: value || '',
      positiveText: positiveButtonTitle,
      negativeText: negativeButtonTitle,
      keyboardType: androidDialogInputType,
      ...androidDialogOptions,
});`

I have two dialogs available next to each other with two different buttons. If i cancel one and try to open the other straight, it will crash consistently.

Using `cancelable` doesn't change anything in this.

**Comment by Eightyplus** [comment]
Hi, is there any solution to this? I'm also getting this error!

with this simple line of code:
`DialogAndroid.alert('Error', `An error occured: ${reason}.`);`

```
2019-11-04 09:13:24.855 23951-23951/com.strimmobile.uat E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.strimmobile.uat, PID: 23951
    java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
        at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:25)
        at com.aakashns.reactnativedialogs.modules.DialogAndroid$4.onClick(DialogAndroid.java:252)
        at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:456)
        at android.view.View.performClick(View.java:6663)
        at android.view.View.performClickInternal(View.java:6635)
        at android.view.View.access$3100(View.java:794)
        at android.view.View$PerformClick.run(View.java:26199)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by Eightyplus** [comment]
Using `import { Alert } from 'react-native';` instead.
